title: Clover-ESP-Legacy
description: Package specially designed for Legacy Bios-based configurations
github:
  repository_url: https://github.com/chris1111/Clover-ESP-Legacy
remote_theme: chris1111/cayman-dark
